import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from "jspdf-autotable";
import { Link, useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
faBars,
faHouse,
faUser,
faUsers,
faCog,
faBell,
faChartBar,
faSignOutAlt,
faDownload,
} from '@fortawesome/free-solid-svg-icons';

const CommitteeReport = () => {
const [sidebarActive, setSidebarActive] = useState(false);
const [committeeDetails, setCommitteeDetails] = useState({});
const [studentDetails, setStudentDetails] = useState({});
const [bursaryInfo, setBursaryInfo] = useState({});
const [userName, setUserName] = useState('');
const [applicationInfo, setApplicationInfo] = useState({});
const navigate = useNavigate();

const toggleSidebar = () => setSidebarActive(!sidebarActive);

useEffect(() => {
const token = sessionStorage.getItem('authToken');
const name = sessionStorage.getItem('userName');
if (!token) {
navigate('/signin');
} else {
setUserName(name);
axios
.get('https://e-bursary-backend.onrender.com/api/comreport', {
headers: { Authorization: token },
})
.then((response) => {
setStudentDetails(response.data);
})
.catch((error) => console.error('Error fetching student data:', error));
}

axios
.get('https://e-bursary-backend.onrender.com/api/committee-count')
.then((response) => {
setBursaryInfo({
totalFunds: response.data.amount,
allocated: response.data.allocated,
remaining: response.data.remaining,
});
})
.catch((error) => console.error('Error fetching bursary info:', error));

axios.get("https://e-bursary-backend.onrender.com/api/committee-statistics", {
      headers: { Authorization: token },
    })
    .then((response) => {
      setApplicationInfo({
        total: response.data.total,
        incomplete: response.data.incomplete,
        approved: response.data.approved,
        rejected: response.data.rejected,
      });
})
.catch((error) => {
  console.error("Error fetching committee statistics:", error);
});
}, [navigate]);

useEffect(() => {
const token = sessionStorage.getItem('authToken');
if (!token) {
navigate('/signin');
} else {
axios
.get('https://e-bursary-backend.onrender.com/api/profile-committee', {
headers: { Authorization: `Bearer ${token}` },
})
.then((response) => {
setCommitteeDetails(response.data);
})
.catch((error) => {
console.error('Error fetching profile data:', error);
});
}
}, [navigate]);

const downloadReport = () => {
const doc = new jsPDF();

doc.setFont('times', 'normal');
doc.setFontSize(25);
doc.text('Bursary Report', 105, 20, null, null, 'center');
doc.setFontSize(20);
doc.text('Generated by Bursary Management System', 105, 30, null, null, 'center');
doc.line(10, 35, 200, 35);

// Personal Information Table
const personalInfo = [
['Reference Number', studentDetails.reference_number || 'N/A'],
['Full Name', studentDetails.fullname || 'N/A'],
['Email', studentDetails.email || 'N/A'],
['Phone No', studentDetails.phone_no || 'N/A'],
['National ID', studentDetails.national_id || 'N/A'],
['Sub County', studentDetails.subcounty || 'N/A'],
['Ward', studentDetails.ward || 'N/A'],
['Position', studentDetails.position || 'N/A'],
];

autoTable(doc, {
startY: 50,
head: [['Personal Information', 'Details']],
body: personalInfo,
theme: 'striped',
headStyles: { fillColor: [41, 128, 185], textColor: [255, 255, 255], fontSize: 14 },
bodyStyles: { fontSize: 12 },
styles: { font: 'times' },
});

// Bursary Information Table
const bursaryData = [
['Total Funds Available', bursaryInfo.totalFunds || 'N/A'],
['Allocated Funds', bursaryInfo.allocated || 'N/A'],
['Remaining Funds', bursaryInfo.remaining || 'N/A'],
];

autoTable(doc, {
startY: doc.lastAutoTable.finalY + 10,
head: [['Bursary Information', 'Details']],
body: bursaryData,
theme: 'grid',
headStyles: { fillColor: [39, 174, 96], textColor: [255, 255, 255], fontSize: 14 },
bodyStyles: { fontSize: 12 },
styles: { font: 'times' },
});

// Application Information Table
const applicationData = [
['Total Applications', applicationInfo.total || 'N/A'],
['Incomplete Applications', applicationInfo.incomplete || 'N/A'],
['Approved Applications', applicationInfo.approved || 'N/A'],
['Rejected Applications', applicationInfo.rejected || 'N/A'],
];

autoTable(doc, {
startY: doc.lastAutoTable.finalY + 10,
head: [['Application Information', 'Details']],
body: applicationData,
theme: 'grid',
headStyles: { fillColor: [192, 57, 43], textColor: [255, 255, 255], fontSize: 14 },
bodyStyles: { fontSize: 12 },
styles: { font: 'times' },
});

// Declaration Table
const declarationInfo = [
['Declaration', 'I hereby confirm the above details are accurate and complete.'],
['Committee Member Name', '________________________'],
['Signature', '________________________'],
['Date', '________________________'],
];

autoTable(doc, {
startY: doc.lastAutoTable.finalY + 20,
head: [['Declaration', '']],
body: declarationInfo,
theme: 'grid',
headStyles: { fillColor: [192, 57, 43], textColor: [255, 255, 255], fontSize: 14 },
bodyStyles: { fontSize: 12, halign: 'left' },
styles: { font: 'times' },
});

doc.setFontSize(10);
doc.text(`Generated on: ${new Date().toLocaleString()}`, 10, 290);
doc.text('Bursary Management System', 105, 290, null, null, 'center');

doc.save('Bursary_Report.pdf');
};

// Prepare report data for mobile-friendly view
const reportRows = [
{ label: 'Reference Number', value: studentDetails.reference_number || 'N/A' },
{ label: 'Application Title', value: 'Committee Report' },
{ label: 'Download Application', value: (
<button
type="button"
onClick={downloadReport}
aria-label="Download Application"
className="bg-transparent border-0 p-0 m-0 cursor-pointer"
>
<FontAwesomeIcon icon={faDownload} className="text-[#14213d] " />
</button>
) },
];

const navItems = [
{ icon: faHouse, label: 'Dashboard', to: '/committeedashboard' },
{ icon: faUser, label: 'Profile', to: '/committeeprofile' },
{ icon: faUsers, label: 'Student Info', to: '/userdetails' },
{ icon: faBell, label: 'Analysis', to: '/committeereport' },
{ icon: faChartBar, label: 'Notification', to: '/committeereport' },
{ icon: faCog, label: 'Settings', to: '/committeesetting' },
{ icon: faSignOutAlt, label: 'Logout', isLogout: true }
];

return (
<div className="w-full min-h-screen relative bg-gradient-to-br from-blue-50 via-white to-purple-50 p-4">

{/* Top Bar */}
<div className="bg-white fixed top-0 left-0 w-full shadow-lg p-2 md:p-2.5 z-50 md:pl-20 md:pr-20">
<div className="flex justify-between items-center">
<h1 className="text-2xl sm:text-3xl md:text-3xl font-bold text-[#14213d]">EBursary</h1>
<div className="flex items-center space-x-1">
<h2 className="mr-1 md:mr-5 text-sm md:text-lg font-bold text-[#14213d]">
Welcome: {committeeDetails.name || userName}
</h2>
<div className="flex items-center space-x-2">
<img
src={
committeeDetails.gender === 'Female'
? '/images/woman.png'
: committeeDetails.gender === 'Male'
? '/images/patient.png'
: '/images/user.png'
}
alt="User"
className="rounded-full w-7 h-7 md:w-9 md:h-9 mr-1 md:mr-0"
/>
</div>
<div className="block md:hidden">
<FontAwesomeIcon
icon={faBars}
className="text-xl cursor-pointer text-[#14213d]"
onClick={toggleSidebar}
/>
</div>
</div>
</div>
</div>
   
<div className="flex flex-col md:flex-row pt-20 min-h-screen">
<div
className={`
fixed top-0 left-0 z-40 bg-[#14213d] text-white h-full mt-10 md:mt-14
transition-all duration-100 ease-in-out
overflow-visible
${sidebarActive ? 'w-[180px] p-4' : 'w-0 p-0'}
${sidebarActive ? 'md:w-[210px] md:p-4' : 'md:w-[36px] md:p-2'}
`}
>
<div className="hidden md:flex justify-end mb-4">
<FontAwesomeIcon
icon={faBars}
className={`text-white cursor-pointer text-text-xl ${sidebarActive ? 'ml-auto' : 'mr-1'}`}
onClick={toggleSidebar}
/>
</div>
<ul className="flex flex-col h-full mt-6 space-y-10">
{navItems.map((item, index) => (
<li className={`group relative ${item.isLogout ? 'mt-30 md:mt-45' : ''}`} key={index}>
{item.isLogout ? (
<a
href="#"
onClick={(e) => {
e.preventDefault();
const token = sessionStorage.getItem('authToken');
axios
.post('https://e-bursary-backend.onrender.com/api/logout', {}, {
headers: { Authorization: `Bearer ${token}` }
})
.catch(() => {})
.finally(() => {
sessionStorage.clear();
navigate('/');
});
}}
className={`flex items-center space-x-2 transition-all duration-200 ${
sidebarActive ? 'justify-start' : 'justify-center'
}`}
>
<FontAwesomeIcon icon={item.icon} className="text-xl" />
<span
className={`${
sidebarActive ? 'inline-block ml-2 font-semibold' : 'hidden'
}`}
>
{item.label}
</span>
</a>
) : (
<Link
to={item.to}
className={`flex items-center space-x-2 transition-all duration-200 ${
sidebarActive ? 'justify-start' : 'justify-center'
}`}
>
<FontAwesomeIcon icon={item.icon} className="text-xl" />
<span
className={`${
sidebarActive ? 'inline-block ml-2 font-semibold' : 'hidden'
}`}
>
{item.label}
</span>
</Link>
)}
{!sidebarActive && (
<span className="absolute left-full ml-5 top-1/2 -translate-y-1/2 bg-[#14213d] text-white font-semibold px-2 py-1 rounded shadow-lg opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity w-[120px] flex items-center justify-center z-50">
{item.label}
</span>
)}
</li>
))}
</ul>
</div>
{/* Main Content Area */}
<div className={`flex-1 ml-0 md:ml-64 md:p-4 mt-0 md:mt-2 transition-all duration-100 md:pr-10 md:pl-10 ${
sidebarActive ? 'ml-[10px] md:ml-[190px]' : 'ml-[0px] md:ml-[10px]'
}`}>
<div className="backdrop-blur-xl bg-white/80 border border-gray-300 shadow-xl rounded-2xl transition-all duration-300 transform hover:scale-[1.01]  max-w-[400px] md:max-w-[800px] mx-auto -mt-4 md:-mt-5 mb-4 md:mb-6 p-1 md:p-8">
<h1 className="text-xl md:text-2xl text-[#14213d] font-bold mb-2 text-center">Bursary Report</h1>
{/* Responsive Report Info: vertical on mobile, table on md+ */}
<div>
{/* Mobile vertical layout */}
<div className="block md:hidden">
{reportRows.map((row) => (
<div key={row.label} className="flex items-center py-2 border-b last:border-b-0">
<span className="font-semibold w-1/2 text-[1rem] bg-[#14213d] text-white px-2 py-1 rounded-1">
{row.label}
</span>
<span className="w-1/2 text-[1rem] bg-white-100 px-2 py-1 rounded-r">
{row.value}
</span>
</div>
))}
</div>
{/* Desktop table layout */}
<div className="hidden md:block w-full overflow-x-auto">
<table className="w-full min-w-[420px] border-collapse bg-white shadow-md rounded">
<thead>
<tr className="bg-[#14213d] text-white text-[1.1rem]">
<th className="p-2 text-left">Reference Number</th>
<th className="p-2 text-left">Application Title</th>
<th className="p-2 text-left">Download Application</th>
</tr>
</thead>
<tbody>
<tr className="border-b text-[1rem]">
<td className="p-2">{studentDetails.reference_number || 'N/A'}</td>
<td className="p-2">Committee Report</td>
<td className="p-2">
<button
type="button"
onClick={downloadReport}
aria-label="Download Application"
className="bg-transparent border-0 p-0 m-0 cursor-pointer"
>
<FontAwesomeIcon
icon={faDownload}
className="text-[#14213d] text-[1.3rem]"
/>
</button>
</td>
</tr>
</tbody>
</table>
</div>
</div>
{/* End Responsive Table Wrapper */}
</div>
</div>
</div>
</div>
);
};

export default CommitteeReport;